Port to Python 3.x
sim0nx/tsl2561 pull request #5
Opened 2017-02-05 15:30 UTC by theFork

I think by now, most people are using Python3.x. For this driver, only a few changes were necessary.

2017-02-05 15:43 UTC, sim0nx requested changes
Hi,

Thanks for your PR.
"Most people", maybe but not all :-)
I would appreciate it if you could just add few small changes to your PR to make it PY2 _and_ PY3 compatible.

In addition to what I posted in the review, also add this to tsl2561.py right below the header:

from __future__ import absolute_import, division, print_function, unicode_literals

Thanks

2017-02-05 15:43 UTC, sim0nx commented on README.md
> -  - python 2.7.x
just add py3 to the list, don't remove py2 completely

2017-02-05 15:43 UTC, sim0nx commented on tsl2561/tsl2561.py
> +#!/usr/bin/python3
If py3 is your default, the original header will still run it with py3, so don't force python3 here

2017-02-06 06:10 UTC, theFork commented
Agreed. I made the changes you suggested.

2017-02-06 18:37 UTC, sim0nx commented
Thanks!

2017-02-06 18:37 UTC, merged